### ISSUE TITLE
CSS 定位

### ISSUE THREAD

**Issue by xieziihang** [xieziihang/React_learn#5]
## 定位简介

**相关属性：**`position`

​	定位是一种更加高级的布局手段，通过定位，我们可以将一个元素摆放到页面的任意位置。

**可选值：**

- `static` 默认值，元素是静止的，没有开启定位
- `relative` 开启元素的相对定位
- `absolute` 开启元素的绝对定位
- `fixed` 开启元素的固定定位
- `sticky` 开启元素的粘滞定位

### 1. 相对定位

**开启：**

​	当元素的 position 属性值设置为 relative 时候，即开启相对定位

**特点：**

- 元素开启相对定位之后，如果不设置偏移量，元素不会发生任何变化

- 偏移量（offset）：元素开启定位之后，可以通过偏移量设置元素的位置 <font color="red">只对开启定位的元素有用</font>
  - top：定位元素和定位位置上面的距离
  - bottom：定位元素和定位位置下边的距离
  - left：定位元素和定位位置左边的距离 （越大越靠右）
  - right：定位元素和定位位置右边的距离（越大越靠左）

- 相对定位是参照于元素在文档流中的位置进行定位的（原始定位位置就是自己）

```css
body {
  font-size: 60px;
}

#box1 {
  width: 200px;
  height: 200px;
  background-color: #bfa;
}

#box2 {
  width: 200px;
  height: 200px;
  position: relative;
  top: -200px;
  left: 200px;
  background-color: orange;
}

#box3 {
  width: 200px;
  height: 200px;
  background-color: yellow;
}
```

```html
  <div id="box1">1</div>
  <div id="box2">2</div>
  <div id="box3">3</div>
```

![image-20220721220452817](https://s2.loli.net/2022/07/21/rfonIQqbOmGp78i.png)

- 相对定位**会提升元素的层级（使得其元素高于文档流中的元素）**
- 相对定位**不会使元素脱离文档流**
- 相对定位**不会改变元素的性质：块元素还是块元素，行内元素还是行内元素**

### 2. 绝对定位

- 开启绝对定位之后，如果不设置偏移量，元素的位置不会发生变化
- 开启绝对定位以后，**元素会从文档流中脱离**
- 绝对定位会改变元素的性质：
  - 内联、行内元素变成块元素（可以设置宽高）
  - 块元素宽高会被内容撑开（宽度不再是包含块的宽度）
- 绝对定位会提升元素的层级
- 定位参照物：
  - 相对于包含块（containing block）进行定位的
    - 正常情况下，包含块就是距离当前元素最近的祖先块元素（1. 祖先 2. 块元素 3. 距离最近）
  - 开启绝对定位元素，其包含块就是**距离其最近的开启了定位的祖先元素**，如果所有祖先元素都没有开启定位，则相对根元素 ( html 元素，初始包含块 )进行定位（1. 距离最近 2. 开启定位 3. 祖先元素）

<font color="red">注意：</font>

​	开启了绝对定位之后，水平方向的布局等式需要添加 left、right 此时规则和之前一样，只是多添加了两个值。

- 发生过度约束（这些值相加不满足等式）时，如果 9 个值中没有 auto，则自动调整 right （原来调整的是 margin-right ）以满足等式，如果有 auto 则自动调整 auto 的值以使等式满足。
  - 可以设置 auto 的值：margin、width、left、right

left + margin-left + border-left + padding-left + width + padding-right + border-left + margin-right + right = 包含块内容区宽度

```css
.box1 {
  width: 500px;
  height: 500px;
  background-color: #bfa;
  position: relative;
}

.box2 {
  width: 100px;
  height: 100px;
  position: absolute;
  background-color: orange;
  margin-left: auto;
  margin-right: auto;
  left: 0px;
  right: 0px;
  /*在这里若 left、right 不设置为 0px 则不会有居中效果，因为 left、right 默认设置为 auto，当 margin-left、margin-right 同样设置为 auto 时候，会优先调整 left、right 以满足等式*/
}
```

```html
<div class="box1">
  <div class="box2"></div>
</div>
```

![image-20220721232509985](https://s2.loli.net/2022/07/21/SBsZLhF23i4l7Wp.png)

- 同时垂直方向等式必须满足

​	left + margin-top + border-top + padding-top + height + padding-bottom + border-bottom  + margin-bottom + bottom  = 包含块内容区高度

```css
.box1 {
  width: 500px;
  height: 500px;
  background-color: #bfa;
  position: relative;
}

.box2 {
  width: 100px;
  height: 100px;
  position: absolute;
  background-color: orange;
  top: 0px;
  bottom: 10px;
  margin-top: auto;
  margin-bottom: auto;
}
```

```html
<div class="box1">
  <div class="box2"></div>
</div>
```

![image-20220722091904925](https://s2.loli.net/2022/07/22/PFy8GxJedoLCcU1.png)

### 3. 固定定位

**开启方式：**

​	将元素的 position 属性设置为 fixed

- 固定定位也是一种绝对定位，其大部分特点和绝对定位一样
  - 唯一不同的是：固定定位永远参照于浏览器的视口进行定位

> 浏览器的可视区域，不会随着滚动条的滚动而变换

### 4. 粘滞定位

**开启方式：**

​	将元素的 position 属性设置为 sticky

- 粘滞定位和相对定位的特点基本一致，不同的是粘滞定位可以在元素到达某个位置时将其固定
